#
# autogenerated by mkdep.sh - DO NOT EDIT
#
hf:  hf-pico.h4 hf-nano.h4 hf.h4
hf-mega:  hf-pico.h4 hf-nano.h4 hf.h4 disasm.h4 BNF.h4 ans.h4 ans-ext.h4 fileio.h4 tools.h4 hf-mega.h4
hf-ans:  hf-pico.h4 hf-nano.h4 hf.h4 disasm.h4 ans.h4 ans-ext.h4 footer.h4 hf-ans.h4
hf-nano:  hf-pico.h4 hf-nano.h4
hf-pico:  hf-pico.h4
plain:  plain.h4
